### ISSUE TITLE
All the plugins refuse to load after a dalamud update. 

### ISSUE THREAD

**Issue by hokeenthong** [NightmareXIV/MyDalamudPlugins#4]
I tried reinstall and re-add. Does not work.

**Comment by Eternita-S** [comment]
Hello!
Please upload your dalamud.log.
It is located at: `%appdata%\XIVLauncher\dalamud.log`

**Comment by hokeenthong** [comment]
[dalamud.log](https://github.com/Eternita-S/MyDalamudPlugins/files/9235397/dalamud.log)

**Comment by hokeenthong** [comment]
Thanks for looking into it.

**Comment by Eternita-S** [comment]
Seems like your plugin setup is having major problems.
I would recommend removing all the plugins and installing them anew. 
Go to `%appdata%\XIVLauncher\installedPlugins` and remove everything from there while game is closed, launch the game once again and reinstall all the plugins you're using. Your configurations will be preserved

**Comment by hokeenthong** [comment]
Thanks!!! It work.
